version: '2'

services:
  mysql:
    image: mysql
    ports:
      - 4361:3306
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "pass123"
      MYSQL_DATABASE: "javengersdb"
    command: ["mysqld",
              "--character-set-server=utf8",
              "--collation-server=utf8_unicode_ci",
              "--init-connect='SET NAMES UTF-8;'",
              "--innodb-flush-log-at-trx-commit=0"]

  wildfly:
    build:
      context: ./web
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 4360:8080
      - 4362:9990
    environment:
      - TZ=Europe/Warsaw